export default {
    SHOW_TOAST: 'SHOW_TOAST',
    HIDE_TOAST: 'HIDE_TOAST',
    SET_SHOW_TOAST: 'SET_SHOW_TOAST',
    INIT_STORE: 'INIT_STORE',
    SET_TOKEN: 'SET_TOKEN',
    REMOVE_TOKEN: 'REMOVE_TOKEN',
    SET_USER_INFO: 'SET_USER_INFO',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
}
